### ISSUE TITLE
Error "unable to find attribute layout_gravity"

### ISSUE THREAD

**Issue by adrielcafe** [loopeer/shadow#1]
Hello!

After add the dependency in my project and build it, gradle throws the below error:
![sem titulo](https://user-images.githubusercontent.com/2512298/30727817-0aaabd1c-9f2a-11e7-8069-371bb2c0cc89.png)

Do you know how to fix it? Thanks!

**Comment by ToDou** [comment]
Try the version 0.0.3. I have fix this layout_gravity problem.

**Comment by adrielcafe** [comment]
Now is working like a charming, thanks @ToDou !
BTW the sample apk is very helpful 😉
