### ISSUE TITLE
ShadowView 四个角有边框

### ISSUE THREAD

**Issue by a56936287** [loopeer/shadow#14]
![qq 20180316170535](https://user-images.githubusercontent.com/14148195/37512205-6bd296ea-293c-11e8-9377-35ac77833a27.jpg)
我复制DEMO里面的代码也是一样的

**Comment by huclengyue** [comment]
同样。。我记得以前没有的。。不知道什么原因

**Comment by huclengyue** [comment]
@a56936287 我试了旧版本是好的，你试试

**Comment by op123355569** [comment]
我也是，只要设置了圆角，就有黑边框，我用的0.0.4-beta2版本，我试了下旧版本，发现很多效果没了，所以还是不行啊，我需要新版本的效果
